inF: 1000G_WGS30X_Unrelated_2504S_rs_Omni.5124_OverlappedMerged_PCs.txt
pcs: range(1, 21)
y_class: Superpopulation
multi_class: True
train_size: 0.75

KBest_k: 10
RFE_n_features_to_select: 10
RFECV_n_splits: 10
PCA_n_component: 10
model_selection_n_splits: 10

train: True
train_model_names: ['RFb']
#train_feature_selection_methods:  ['KBest', 'RFE', 'RFECV', 'SFM', 'PCA']
train_feature_selection_methods:  ['KBest', 'RFE', 'RFECV', 'SFM', 'PCA']
#train_feature_selection_methods:  ['None']
confusion_matrix: False

test: True
test_model_name: RFb
test_feature_selection_method: None

predict: True
